BDB Agena Configs
KSP-RO/RealismOverhaul pull request #2805
Opened 2023-03-24 14:56 UTC by SkyPhoenix999

RO Configs for Agena from BDB

2023-04-07 03:27 UTC, Capkirk123 requested changes
A good start, but could use some work. It looks like there wasn't much of an attempt to set masses for a lot of these parts.

You should look at the existing configs for these parts, either in ROCapsules or the old configs section, a lot of them were already configured pretty well.

2023-04-07 03:27 UTC, Capkirk123 commented on GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/Agena/RO_Agena.cfg
> +	%useRcsConfig = RCSBlockTenth
Too weak (and probably too light), this was a spare Gemini Reentry Control system, which was fitted with 25 lbf thrusters

2023-04-07 03:27 UTC, Capkirk123 commented on GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/Agena/RO_Agena.cfg
> +	@mass = 0.05
This should be 211 kg to match ROCapsules

2023-04-07 03:27 UTC, Capkirk123 commented on GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/Agena/RO_Agena.cfg
> +		@nodeType = Gemini
This should be GeminiAgena to match ROCapsules

2023-04-07 03:27 UTC, Capkirk123 commented on GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/Agena/RO_Agena.cfg
> +	@description = Essentially a pen light on the end of a straw, this light (traditionally mounted to the decoupler ring on the Apollo CSM) swings out to provide illumination to aid kerbonauts on EVAs.
Did you put the wrong description here?

2023-04-07 03:27 UTC, Capkirk123 commented on GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/Agena/RO_Agena.cfg
> +				{
Should be about 30 liters per tank.

2023-04-07 03:27 UTC, Capkirk123 commented on GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/Agena/RO_Agena.cfg
> +	@MODULE[ModuleRCSFX]
RCS ISP is too high for HTP

2023-04-07 03:27 UTC, Capkirk123 commented on GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/Agena/RO_Agena_Engines.cfg
> +		name = ModuleB9DisableTransform
You should use this nozzle config

2023-04-07 03:27 UTC, Capkirk123 commented on GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/Agena/RO_Agena_Engines.cfg
> +	@title = XLR81 Agena Engine Series
There's no reason to rename this

2023-04-07 03:27 UTC, Capkirk123 commented on GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/Agena/RO_Return_Capsules.cfg
> +		{
This is too high for an HTP thruster

2023-04-07 03:27 UTC, Capkirk123 commented on GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/Agena/RO_Strawman.cfg
> +		name = ModuleRealAntenna
You should actually configure these as high gain antennas

2023-04-07 03:27 UTC, Capkirk123 commented on GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/Agena/RO_Agena.cfg
> +	@mass = 0.1
Could you try to configure these a bit better instead of setting them all the same?

2023-12-02 20:16 UTC, Capkirk123 commented
Oh, and following recent attempts to get rid of massless batteries, _don't use SM tanks for anything that shouldn't have a battery in it, especially if that tank is massless_

2023-12-03 20:36 UTC, Capkirk123 approved these changes

2024-08-11 12:25 UTC, SkyPhoenix999 reviewed
Works in Game. Forgot I reviewed myself

2026-05-18 02:56 UTC, merged