Benjee10_SharedAssets RO Configs
KSP-RO/RealismOverhaul pull request #2966
Opened 2024-05-29 12:55 UTC by SkyPhoenix999

Used in multiple mods and needs to be standardized as such.

Covers the CBM, NDS/APAS/IDA, SSPV, and AJ10

Used in (almost) all Benjee10 Mods such as HabTech2, ACK, SOCK, MSSEV, etc

2024-06-12 00:26 UTC, Capkirk123 commented
Everything should now be scaled to the correct size. However, the scale for these parts is being set elsewhere in the mod configs (notably in the Habtech 2 configs), which means the settings from these configs are not being applied. Configs other than this one should probably be removed since these parts live in Benjee10 shared assets

2024-06-12 13:07 UTC, SkyPhoenix999 commented
This line is what overrides the rescale factor in Benjee's other mods, idk why he put two separate rescaleFactors in some of his parts but this fixes it
`!rescaleFactor,* = DEL`

I can verify your NDS rescale values but not your CBM values, the 1.8x values were properly sized (and additionally are properly sized for HabTech2 at that value)

The outer ring diameter is 82 inches (2.083m) not 79 inches, [Per This Document](https://imlive.s3.amazonaws.com/Federal%20Government/ID42272755263273611130549092035837226177/SSP41148.pdf), 79 inches refers to the inner diameter, this 1.6737x rescale value is far too small. Should be between 1.7437x and 1.8x. depending on if you want to scale for inner diameter or outer. I chose 1.8x for consistency with HabTech parts while being within the correct size range.

2024-06-13 00:22 UTC, Capkirk123 commented
I used Freedom-era documents for reference, so it's possible that they were changed.

The issue is not Benjee10s other mods, it is other RO configs. The rescaleFactors being set in this config are being changed by other rescale factors in other RO configs. They should be removed.

2024-06-17 23:47 UTC, Capkirk123 commented
Well if the Habtech 2 configs are outdated, that's all the more reason to delete them in favor of the not-outdated configs here

2024-06-17 23:48 UTC, Capkirk123 requested changes
Removing competing configs for Benjee10 shared assets parts (namely, those in Habtech2)

2024-06-18 11:08 UTC, SkyPhoenix999 commented
I have a new set of HabTech configs but I still have some B9 errors to sort out, and I might wait until the new update with the large modules comes out, I'm undecided on that.

2024-06-18 21:55 UTC, Capkirk123 commented
I have decided for you

2024-06-18 21:55 UTC, Capkirk123 approved these changes

2024-06-18 22:23 UTC, SkyPhoenix999 commented
One Last thing, NDS Passive Port. Good to go now.

2024-06-19 21:39 UTC, merged